import { AppShell } from "@/components/app-shell";
import { DemoScanLauncher } from "@/components/demo-scan-launcher";

export default function Home() {
  const workflow = ["Repository", "Deterministic Security Engine", "Evidence Package", "AI Security Review", "Dashboard"];
  const trustPoints = ["Static analysis only", "Repository code is never executed", "Public GitHub HTTPS repositories only", "Secret values are redacted", "Deterministic findings remain authoritative", "AI guidance is advisory", "Patches require human review"];

  return <AppShell><DemoScanLauncher /><section className="scroll-mt-24 border-t border-white/[.08]" id="architecture"><div className="mx-auto max-w-7xl px-5 py-12 lg:px-8"><p className="font-mono text-xs uppercase tracking-wider text-emerald-300">Architecture and trust boundary</p><h2 className="mt-3 text-3xl font-semibold">Evidence first. AI guidance second.</h2><ol className="mt-7 grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-5">{workflow.map((step, index) => <li className="relative rounded-xl border border-white/[.1] bg-[#0c141f] p-4 text-slate-200" key={step}><span className="font-mono text-xs text-emerald-300">{index + 1}</span><span className="mt-2 block font-semibold">{step}</span>{index < workflow.length - 1 ? <span aria-hidden="true" className="absolute -right-3 top-1/2 hidden text-xl text-emerald-300 lg:block">→</span> : null}</li>)}</ol><ul className="mt-7 grid gap-3 text-sm text-slate-400 sm:grid-cols-2 lg:grid-cols-3">{trustPoints.map((point) => <li className="rounded border border-white/[.08] bg-[#0c141f] px-3 py-2" key={point}>✓ {point}</li>)}</ul><p className="mt-6 text-sm leading-6 text-slate-500">Sentinel’s security coverage is intentionally bounded and does not represent a comprehensive security assessment.</p></div></section></AppShell>;
}
