"use client";
import { useEffect, useRef, useState } from "react";
import { FindingsList } from "./findings-list";
import { FindingDetails } from "./finding-details";
import { ScanProgress } from "./scan-progress";
import { SecuritySummary } from "./security-summary";
import type { Finding, ScanResponse } from "@/lib/scan-types";
import { loadDemoScan } from "@/lib/demo-scan-service";

type State = { kind: "idle" } | { kind: "review-empty" } | { kind: "loading" } | { kind: "error"; message: string } | { kind: "ready"; scan: ScanResponse; selected: Finding | null };

export function DemoScanLauncher() {
  const [state, setState] = useState<State>({ kind: "idle" });
  const reviewRef = useRef<HTMLDivElement>(null);
  useEffect(() => { const handleNavigation = (event: Event) => { const destination = (event as CustomEvent<"overview" | "review" | "architecture">).detail; if (destination === "overview") { setState({ kind: "idle" }); window.scrollTo({ top: 0, behavior: "smooth" }); } if (destination === "review") { if (state.kind === "ready") reviewRef.current?.scrollIntoView({ behavior: "smooth" }); else setState({ kind: "review-empty" }); } if (destination === "architecture") document.getElementById("architecture")?.scrollIntoView({ behavior: "smooth" }); }; window.addEventListener("sentinel:navigate", handleNavigation); return () => window.removeEventListener("sentinel:navigate", handleNavigation); }, [state.kind]);
  async function start() { setState({ kind: "loading" }); try { const scan = await loadDemoScan(); setState({ kind: "ready", scan, selected: scan.findings[0] ?? null }); } catch { setState({ kind: "error", message: "The bundled demo scan is currently unavailable. Retry when the Sentinel API is ready." }); } }
  if (state.kind === "loading") return <div id="overview" className="mx-auto max-w-7xl px-5 py-12 lg:px-8"><ScanProgress onCancel={() => setState({ kind: "idle" })} /></div>;
  if (state.kind === "ready") return <div className="mx-auto max-w-7xl px-5 py-12 lg:px-8" ref={reviewRef}><SecuritySummary scan={state.scan} /><FindingsList findings={state.scan.findings} onSelect={(selected) => setState({ ...state, selected })} />{state.selected ? <FindingDetails ai={state.scan.ai} finding={state.selected} /> : null}</div>;
  if (state.kind === "review-empty") return <section className="mx-auto max-w-7xl px-5 py-16 lg:px-8" id="review"><p className="font-mono text-xs uppercase tracking-[.16em] text-emerald-300">Security review</p><h1 className="mt-3 text-4xl font-semibold">No scan is open</h1><p className="mt-4 max-w-xl text-slate-400">Run the bundled TaskFlow AI demo to view deterministic authorization analysis. Sentinel does not retain scan history.</p><button className="mt-7 rounded-lg bg-emerald-300 px-5 py-3 font-semibold text-slate-950" onClick={() => void start()} type="button">Run TaskFlow Demo Scan</button></section>;
  return <section className="mx-auto grid max-w-7xl gap-10 px-5 py-16 lg:grid-cols-[1.2fr_.8fr] lg:px-8 lg:py-24" id="overview"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-emerald-300">Bundled vulnerable demo: TaskFlow AI</p><h1 className="mt-4 max-w-3xl text-5xl font-semibold tracking-tight text-white sm:text-6xl">Detect authorization vulnerabilities. Understand their impact. Review secure remediation.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-400">Deterministic authorization analysis for TypeScript, Express, and Prisma applications. This intentionally vulnerable repository demonstrates BOLA detection.</p><button className="mt-8 rounded-lg bg-emerald-300 px-5 py-3 font-semibold text-slate-950 focus:outline-none focus:ring-2 focus:ring-emerald-100" onClick={() => void start()} type="button">Run TaskFlow Demo Scan</button>{state.kind === "error" ? <div className="mt-5 rounded border border-rose-400/30 bg-rose-400/10 p-4 text-sm text-rose-100" role="alert">{state.message}<button className="ml-4 underline" onClick={() => void start()} type="button">Retry</button></div> : null}</div><aside className="rounded-xl border border-white/[.08] bg-[#0c141f] p-6"><p className="font-mono text-xs uppercase tracking-wider text-slate-500">Current scanner scope</p><ul className="mt-5 space-y-3 text-sm text-slate-300">{["Route and authentication discovery", "Prisma model and route-to-model mapping", "Ownership-field analysis", "Deterministic BOLA / IDOR findings", "Optional GPT-5.6 explanation"].map((item) => <li key={item}>✓ {item}</li>)}</ul><p className="mt-6 text-sm text-slate-500">Broader OWASP coverage is future work. GitHub repositories and ZIP upload are not available yet.</p></aside></section>;
}
