"use client";
import { useState } from "react";
import type { AIAnalysis, Finding } from "@/lib/scan-types";
import { CategoryBadge } from "./findings-list";

type Tab = "Overview" | "Evidence" | "AI Explanation" | "Remediation" | "Patch" | "Verification";
const tabs: Tab[] = ["Overview", "Evidence", "AI Explanation", "Remediation", "Patch", "Verification"];

export function FindingDetails({ finding, ai, initialTab = "Overview" }: { finding: Finding; ai: AIAnalysis; initialTab?: Tab }) {
  const [tab, setTab] = useState<Tab>(initialTab); const result = ai.results.find((item) => item.finding_id === finding.finding_id);
  return <section aria-labelledby="detail-title" className="mt-8 overflow-hidden rounded-xl border border-white/[.08] bg-[#0c141f] p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div className="min-w-0"><p className="break-all font-mono text-xs text-slate-500">{finding.finding_id} · {finding.rule_id}</p><h2 className="mt-1 break-words text-2xl font-semibold" id="detail-title">{finding.title}</h2></div><div className="flex flex-wrap gap-2"><CategoryBadge category={finding.category} /><span className="rounded-full border border-orange-300/30 px-3 py-1 text-sm font-medium capitalize text-orange-100">{finding.severity} · risk {finding.risk_score}</span></div></div><div className="mt-6 flex overflow-x-auto border-b border-white/[.08]" role="tablist">{tabs.map((item) => <button aria-controls={`detail-${item}`} aria-selected={tab === item} className={`shrink-0 border-b-2 px-3 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-emerald-300 ${tab === item ? "border-emerald-300 text-emerald-300" : "border-transparent text-slate-400"}`} key={item} onClick={() => setTab(item)} role="tab" type="button">{item}</button>)}</div><div className="pt-5 text-sm leading-6 text-slate-300" id={`detail-${tab}`} role="tabpanel">{tab === "Overview" && <Overview finding={finding} />}{tab === "Evidence" && <Evidence finding={finding} />}{tab === "AI Explanation" && <AIExplanation ai={ai} result={result} />}{tab === "Remediation" && <Remediation result={result} />}{tab === "Patch" && <Patch result={result} />}{tab === "Verification" && <Verification result={result} />}</div></section>;
}

function Overview({ finding }: { finding: Finding }) { const facts = [["Status", "Open"], ["Confidence", `${Math.round(finding.confidence * 100)}%`], ...(finding.method ? [["Method", finding.method]] : []), ...(finding.path ? [["Route", finding.path]] : []), ...(finding.model ? [["Model", finding.model]] : []), ...(finding.operation && finding.operation !== "unknown" ? [["Operation", finding.operation]] : []), ...(finding.ownership_candidate ? [["Ownership candidate", finding.ownership_candidate]] : []), ["Source", `${finding.source_file}:${finding.line_number}`], ...(finding.cwe.length ? [["CWE", finding.cwe.join(", ")]] : []), ...(finding.owasp.length ? [["OWASP", finding.owasp.join(", ")]] : [])]; return <><p>{finding.description}</p><dl className="mt-5 grid gap-3 sm:grid-cols-2">{facts.map(([label, value]) => <div className="rounded border border-white/[.08] p-3" key={label}><dt className="font-mono text-[10px] uppercase tracking-wider text-slate-500">{label}</dt><dd className="mt-1 break-words text-slate-200">{value}</dd></div>)}</dl></>; }
function Evidence({ finding }: { finding: Finding }) { return <><p className="font-mono text-xs uppercase tracking-wider text-emerald-300">Deterministic evidence</p><ul className="mt-3 space-y-2">{finding.evidence.map((item) => <li className="break-words" key={item}>• {item}</li>)}</ul><p className="mt-6 font-mono text-xs uppercase tracking-wider text-slate-500">Risk score components</p><ul className="mt-3 grid gap-2 sm:grid-cols-2">{finding.risk_components.map((item) => <li className="rounded border border-white/[.08] p-2" key={item.name}>{item.name}: +{item.points}</li>)}</ul></>; }
function AIExplanation({ ai, result }: { ai: AIAnalysis; result: AIAnalysis["results"][number] | undefined }) { if (ai.status === "disabled") return <p>AI explanation is disabled. Deterministic findings remain available.</p>; if (ai.status === "unavailable") return <p>AI explanation could not be generated. The security finding is unaffected.</p>; if (!result) return <p>{ai.status === "partial" ? "Some AI guidance could not be generated." : "AI explanation could not be generated. The security finding is unaffected."}</p>; return <dl className="space-y-4">{[["Summary", result.explanation.summary], ["Technical explanation", result.explanation.technical_explanation], ["Root cause", result.root_cause], ["Business impact", result.explanation.business_impact], ["Why detected", result.explanation.why_detected], ["Confidence reasoning", result.explanation.confidence_reasoning], ["False-positive notes", result.explanation.false_positive_notes]].map(([label, value]) => <div key={label}><dt className="font-mono text-xs uppercase tracking-wider text-slate-500">{label}</dt><dd className="mt-1">{value}</dd></div>)}</dl>; }
function Remediation({ result }: { result: AIAnalysis["results"][number] | undefined }) { return !result ? <p>AI remediation is unavailable. Review the deterministic recommendation before making changes.</p> : <><p>Priority: <b>{result.remediation.priority}</b> · Strategy: <b>{result.remediation.strategy}</b></p><ol className="mt-4 list-decimal space-y-2 pl-5">{result.remediation.steps.map((step) => <li key={step}>{step}</li>)}</ol><p className="mt-5 text-slate-400">Security considerations: review the change in context and preserve existing authentication controls.</p></>; }
function Patch({ result }: { result: AIAnalysis["results"][number] | undefined }) { return !result ? <p>No patch proposal is available. Patches are never applied automatically.</p> : <><p className="font-mono text-xs uppercase tracking-wider text-amber-200">Review-required patch proposal</p><p className="mt-2 break-all">Target: {result.patch.source_file}</p><pre className="mt-4 overflow-x-auto whitespace-pre-wrap break-words rounded border border-white/[.08] bg-black/30 p-4 text-xs text-slate-300"><code>{result.patch.diff}</code></pre><p className="mt-3 text-slate-400">Human review is required before any patch is applied.</p></>; }
function Verification({ result }: { result: AIAnalysis["results"][number] | undefined }) { return !result ? <p>No verification checklist is available. Automatic fix verification belongs to the next milestone.</p> : <><ul className="space-y-2">{result.verification.items.map((item) => <li key={item.check}>[{item.required ? "manual check required" : "optional"}] {item.check}</li>)}</ul><p className="mt-5 text-slate-400">Automated remediation verification belongs to the next milestone.</p></>; }
