"use client";
import { useMemo, useState } from "react";
import type { Finding, Severity } from "@/lib/scan-types";

export function FindingsList({ findings, onSelect }: { findings: Finding[]; onSelect: (finding: Finding) => void }) {
  const [query, setQuery] = useState(""); const [severity, setSeverity] = useState<Severity | "all">("all");
  const filtered = useMemo(() => findings.filter((finding) => (severity === "all" || finding.severity === severity) && `${finding.rule_id} ${finding.title} ${finding.path}`.toLowerCase().includes(query.toLowerCase())), [findings, query, severity]);
  return <section className="mt-10" aria-labelledby="findings-title"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-mono text-xs uppercase tracking-[.16em] text-orange-300">Deterministic findings</p><h2 className="mt-2 text-2xl font-semibold" id="findings-title">Authorization review</h2></div><div className="flex gap-2"><input aria-label="Search findings" className="w-40 rounded border border-white/[.12] bg-[#0c141f] px-3 py-2 text-sm" onChange={(event) => setQuery(event.target.value)} placeholder="Search findings" value={query} /><select aria-label="Filter severity" className="rounded border border-white/[.12] bg-[#0c141f] px-2 text-sm" onChange={(event) => setSeverity(event.target.value as Severity | "all")} value={severity}><option value="all">All severities</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></div></div>{filtered.length === 0 ? <p className="mt-5 rounded border border-white/[.08] p-5 text-sm text-slate-400">No findings match this review.</p> : <div className="mt-5 overflow-x-auto rounded-xl border border-white/[.08]"><table className="min-w-[760px] w-full text-left text-sm"><thead className="bg-white/[.03] font-mono text-[10px] uppercase tracking-wider text-slate-500"><tr>{["Severity", "Rule", "Finding", "Route", "Model", "Risk", "Confidence", "Status"].map((label) => <th className="p-3" key={label}>{label}</th>)}</tr></thead><tbody>{filtered.map((finding) => <tr className="border-t border-white/[.08]" key={finding.finding_id}><td className="p-3 text-orange-200">{finding.severity}</td><td className="p-3 font-mono">{finding.rule_id}</td><td className="p-3"><button className="text-left text-emerald-300 underline-offset-4 hover:underline focus:outline-none focus:ring-2 focus:ring-emerald-300" onClick={() => onSelect(finding)} type="button">{finding.title}</button></td><td className="p-3 font-mono">{finding.method} {finding.path}</td><td className="p-3">{finding.model}</td><td className="p-3">{finding.risk_score}</td><td className="p-3">{Math.round(finding.confidence * 100)}%</td><td className="p-3">Open</td></tr>)}</tbody></table></div>}</section>;
}
